version: '3.8'

services:
  mongo-staging:
    build:
      context: .
      dockerfile: Dockerfile.staging
    ports:
      - "27020:27019"
    environment:
      - MONGO_USER=${MONGO_USER}
      - MONGO_PASSWORD=${MONGO_PASSWORD}
    volumes:
      - mongo-staging-data:/data/db
      - ./logs:/var/log/mongodb
  mongo-development:
      build:
        context: .
        dockerfile: Dockerfile.development
      ports:
        - "27022:27019"
      environment:
        - MONGO_USER=${MONGO_USER}
        - MONGO_PASSWORD=${MONGO_PASSWORD}
      volumes:
        - mongo-development-data:/data/db
        - ./logs:/var/log/mongodb
volumes:
  mongo-staging-data:
  mongo-development-data:
