FROM gradle:8.14.3-jdk17-alpine AS build
WORKDIR /app
COPY . .
RUN gradle clean build --no-daemon -x test

FROM openjdk:17-alpine
WORKDIR /app
RUN apk add --no-cache python3 py3-pip curl && \
  pip3 install --no-cache-dir awscli

RUN mkdir -p /certs
ARG CA_PATH
COPY certs/mongo-ca.pem /certs/mongo-ca.pem
COPY --from=build /app/build/libs/*.jar app.jar

COPY entrypoint-staging.sh /app/entrypoint.sh
RUN chmod +x /app/entrypoint.sh
ENTRYPOINT ["/app/entrypoint.sh"]