FROM gradle:8.14.3-jdk17-alpine AS build
WORKDIR /app
COPY . .
RUN gradle clean build --no-daemon -x test

FROM eclipse-temurin:17-jdk-alpine-3.22
WORKDIR /app
# RUN apk add --no-cache python3 py3-pip curl && \
#   pip3 install --no-cache-dir awscli -- convert to linux/amd64

# Install python3, pip, curl, unzip
RUN apk add --no-cache python3 py3-pip bash curl unzip

# Create virtual environment for awscli
RUN python3 -m venv /opt/awscli \
  && /opt/awscli/bin/pip install --no-cache-dir awscli

# Add awscli to PATH
ENV PATH="/opt/awscli/bin:$PATH"

# Verify installation
RUN python3 --version \
  && aws --version

RUN mkdir -p /certs
ARG CA_PATH
COPY certs/mongo-ca.pem /certs/mongo-ca.pem
COPY --from=build /app/build/libs/*.jar app.jar

COPY entrypoint-staging.sh /app/entrypoint.sh
RUN chmod +x /app/entrypoint.sh
ENTRYPOINT ["/app/entrypoint.sh"]